version: '3'
services:
  server:
    build: .
    command: yarn start
    ports:
      - '3000:3000'
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - /app/node_modules
