version: '3'
services:
  server:
    build: .
    command: yarn start
    ports:
      - '5000:5000'
      - '5001:5001'
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - /app/node_modules
