version: '3'
services:
  mongo:
    image: mongo:3.4.4

    networks:
      - gql
  server:
    build: .
    command: yarn start
    ports:
      - '3000:3000'
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - gql

networks:
  gql:
